Frontends/CovCourse.Web/Controllers/AuthController.cs
using CovCourse.Web.Models;
using CovCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace CovCourse.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IIdentityService _identityService;

        public AuthController(IIdentityService identityService)
        {
            _identityService = identityService;
        }

        public IActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignIn(SignInInput signInInput)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var response = await _identityService.SignIn(signInInput);
            if (!response.IsSuccessful)
            {
                if (response.Errors != null && response.Errors.Count>0)
                {
                    response.Errors.ForEach(error => { ModelState.AddModelError(string.Empty, error); });
                }
                else
                {
                   ModelState.AddModelError(string.Empty, "Email or Password Wrong !");
                }
              
                return View();
             
            }
            return RedirectToAction(nameof(Index), "Home");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await _identityService.RefreshToken();
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

Frontends/CovCourse.Web/Controllers/BasketController.cs
using CovCourse.Web.Models.Baskets;
using CovCourse.Web.Models.Discounts;
using CovCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CovCourse.Web.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly IBasketService _basketService;

        public BasketController(ICatalogService catalogService, IBasketService basketService)
        {
            _catalogService = catalogService;
            _basketService = basketService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _basketService.Get());
        }

        public async Task<IActionResult> AddBasketItem(string courseId)
        {
            var course = await _catalogService.GetAllCourseByIdAsync(courseId);
            var basketItem = new BasketItemViewModel { CourseId = courseId ,CourseName=course.Name,Price=course.Price };

            await _basketService.AddBasketItem(basketItem);

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> DeleteBasketItem(string courseId)
        {
           await _basketService.RemoveBasketItem(courseId);
           return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ApplyDiscount(DiscountApplyInput discountApplyInput)
        {
            //var discountStatus = await _basketService.ApplyDiscount(discountApply.Code);
            //TempData["discountStatus"] = discountStatus;
            //return RedirectToAction(nameof(Index));
            if (!ModelState.IsValid)
            {
                TempData["discountError"] = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).First();
                return RedirectToAction(nameof(Index));
            }
            var discountStatus = await _basketService.ApplyDiscount(discountApplyInput.Code);

            TempData["discountStatus"] = discountStatus;
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> CancelApplyDiscount()
        {
            await _basketService.CancelApplyDiscount(); 
            return RedirectToAction(nameof(Index));
        }

    }
}

Frontends/CovCourse.Web/Controllers/OrderController.cs
using CovCourse.Web.Models.Orders;
using CovCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CovCourse.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public OrderController(IBasketService basketService, IOrderService orderService)
        {
            _basketService = basketService;
            _orderService = orderService;
        }
        [HttpGet]
        public async Task<IActionResult> CheckOut()
        {
            var basket = await _basketService.Get();
            ViewBag.basket = basket;

            return View(new CheckoutInfoInput());
        }
        [HttpPost]
        public async Task<IActionResult> CheckOut(CheckoutInfoInput checkoutInfoInput)
        {
            //First way - sync
            //var orderStatus = await _orderService.CreateOrder(checkoutInfoInput);

            //Second way - async
            var orderSuspend = await _orderService.SuspendOrder(checkoutInfoInput);

            if (!orderSuspend.isSuccessful)
            {
                var basket = await _basketService.Get();
                ViewBag.basket = basket;
                ViewBag.error = orderSuspend.Error;
                return View();
            }
            //First way - sync
            // return RedirectToAction(nameof(SuccessfulResult),new {orderId= orderSuspend.OrderId});

            //Second way - async
            return RedirectToAction(nameof(SuccessfulResult),new {orderId= new Random().Next(1,1000)});
        }
        public IActionResult SuccessfulResult(int orderId)
        {
            ViewBag.orderId = orderId; 
            return View();
        }
        public async Task<IActionResult> CheckoutHistory()
        {
            var orders = await _orderService.GetOrder();

         
           return View(orders);
        }
    }
}

Frontends/CovCourse.Web/Controllers/UserController.cs
using CovCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CovCourse.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;


        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userService.GetUser());
        }
    }
}

Frontends/CovCourse.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CovCourse.Web</title>
	<link href="~/lib/bootstrap-5.3.3/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CovCourse.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CovCourse.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    @if(User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="User" asp-action="Index">Profile</a></li>
                                    <li><a class="dropdown-item" asp-controller="Order" asp-action="CheckoutHistory">Purchase History</a></li>
                                    <li><a class="dropdown-item" asp-controller="Basket" asp-action="Index">Basket</a></li>
                                    <li><a class="dropdown-item" asp-controller="Auth" asp-action="LogOut">Log out</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="SignIn">Log in</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CovCourse.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap-5.3.3/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>